#!/bin/bash
## output directory
echo --- creating output directory ---
basedir=/mnt/d/devtool/GISTIC2/output/BRCA
mkdir -vp $basedir
echo --- running GISTIC ---
## input file definitions
segfile=`pwd`/input/BRCA_MaskedCopyNumberSegment.txt
markersfile=`pwd`/input/hg38_marker_file.txt
refgenefile=/mnt/d/devtool/GISTIC2/refgenefiles/hg38.UCSC.add_miR.160920.refgene.mat
## call script that sets MCR environment and calls GISTIC executable
./gistic2 -b $basedir -seg $segfile -mk $markersfile -refgene $refgenefile -alf $alf -cnv $cnvfile -genegistic 1 -smallmem 1 -broad 1 -brlen 0.5 -conf 0.99 -armpeel 1 -savegene 1 -gcm extreme
